version: 1.0.{build}

image:
- Ubuntu2004

build: off

init:

#cache:
        ##- boringssl -> appveyor-linux.yml # we define the commit in here

install:

- sh: >-

    if [[ -e boringssl/CMakeLists.txt ]] ; then

        echo cached

    else

        #git clone https://boringssl.googlesource.com/boringssl

        #cd boringssl

        #git checkout a2278d4d2cabe73f6663e3299ea7808edfa306b9

        cmake .

        make -j4 cmake-build-debug/Makefile

        cd ..

    fi

    #git submodule init

    #git submodule update --checkout --force --recursive

    #cmake -DBORINGSSL_DIR=$PWD/boringssl .

    #make

#test_script:
        #- sh: make test
