version: 1.0.{build}

image:
- Ubuntu2004

build: off

skip_commits:
  message: /\[unsurveilled\]/

init:

#cache:
        ##- boringssl -> appveyor-linux.yml # we define the commit in here

install:

- sh: >-

    if [[ -e boringssl/CMakeLists.txt ]] ; then

        echo cached

    else

        echo "About to download OpenMPI 4"

        wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz

        tar xvzf https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz

        cd openmpi-4.1.2

        ./configure |& tee config.out

        make -j 8 |& tee make.out

        make install |& tee install.out
        
        cd ..

        echo "About to download Boost 1.77.0"

        wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
        
        tar zxvf boost_1_77_0.tar.gz
        
        cd boost_1_77_0
        
        ./bootstrap.sh
        
        ./b2 install

        cd ..

        echo "About to build the project :-)"

        wget https://github.com/GastonMazzei/NEDISS/archive/refs/heads/main.zip

        unzip main.zip

        cd NEDISS-main

        cmake -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build

        cmake --build ./build -- -j4

        cd ..

        echo "Ended succesfully :-)"

    fi

    #git submodule init

    #git submodule update --checkout --force --recursive

    #cmake -DBORINGSSL_DIR=$PWD/boringssl .

    #make

#test_script:
        #- sh: make test
